import React, { useState, useEffect } from 'react';
import {
  ArrowLeft,
  Volume2,
  VolumeX,
  PhoneCall,
  Copy,
  CheckCheck,
  Flame,
  Zap,
  Droplets,
  ShieldAlert,
  HeartPulse,
  Wind,
  Activity,
  Biohazard,
  FileText,
  AlertTriangle,
  Radio,
  MapPin,
  Sparkles,
  Hospital,
} from 'lucide-react';
import { EmergencyResponse } from '../types';
import { RiskBadge } from './RiskBadge';
import { ActionList } from './ActionList';
import { AvoidList } from './AvoidList';
import { NextStepCard } from './NextStepCard';
import { RestartButton } from './RestartButton';
import { OfflineLocationBeacon } from './OfflineLocationBeacon';
import { VisualStrobeSignal } from './VisualStrobeSignal';
import { CrisisToolRouter } from './specialized/CrisisToolRouter';
import { Emergency911DispatchScript } from './Emergency911DispatchScript';
import { MultilingualCrisisAlert } from './MultilingualCrisisAlert';

interface ResultScreenProps {
  assessment: EmergencyResponse;
  onReset: () => void;
  onNewAssessment: () => void;
  onGoToNextStep: () => void;
  onOpenIceModal?: () => void;
  onOpenLiveDashboard?: () => void;
  onOpenSos?: () => void;
  onOpenNearbyHelp?: () => void;
}

export const ResultScreen: React.FC<ResultScreenProps> = ({
  assessment,
  onReset,
  onNewAssessment,
  onGoToNextStep,
  onOpenIceModal,
  onOpenLiveDashboard,
  onOpenSos,
  onOpenNearbyHelp,
}) => {
  const [copied, setCopied] = useState(false);
  const [completedSteps, setCompletedSteps] = useState<number[]>([]);
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);
  const [synthSupported, setSynthSupported] = useState(false);

  useEffect(() => {
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      setSynthSupported(true);
    }
    return () => {
      if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
        window.speechSynthesis.cancel();
      }
    };
  }, []);

  const handleCopyPlan = () => {
    const textToCopy = `CRISISMATE EMERGENCY DIRECTIVE: ${assessment.emergencyType} [Risk: ${assessment.riskLevel}]
    
DO THIS NOW:
${assessment.doNow.map((item, idx) => `${idx + 1}. ${item}`).join('\n')}

CRITICAL RULE:
${assessment.keySafetyRule || 'Follow standard evacuation procedures.'}

AVOID:
${assessment.avoid.map((item) => `- ${item}`).join('\n')}

NEXT STEP:
${assessment.nextStep}

DISPATCH SCRIPT:
${assessment.dispatchScript || 'Request immediate EMS / Fire / Police response.'}

Generated by CrisisMate Emergency Decision Assistant.`;

    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleTextToSpeech = () => {
    if (!synthSupported) return;

    if (isPlayingAudio) {
      window.speechSynthesis.cancel();
      setIsPlayingAudio(false);
      return;
    }

    window.speechSynthesis.cancel();

    const text = `Emergency Alert: ${assessment.emergencyType}. Risk level: ${assessment.riskLevel}. Priority one: ${assessment.doNow.join('. ')}. Critical safety warning: avoid ${assessment.avoid.join(', ')}.`;

    const utterance = new SpeechSynthesisUtterance(text);
    utterance.rate = 1.05;
    utterance.pitch = 1.0;
    utterance.onend = () => setIsPlayingAudio(false);
    utterance.onerror = () => setIsPlayingAudio(false);

    setIsPlayingAudio(true);
    window.speechSynthesis.speak(utterance);
  };

  const toggleStep = (index: number) => {
    setCompletedSteps((prev) =>
      prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index]
    );
  };

  const getEmergencyIcon = () => {
    switch (assessment.category) {
      case 'fire':
        return <Flame className="w-7 h-7 text-red-500" />;
      case 'electrical':
        return <Zap className="w-7 h-7 text-amber-500" />;
      case 'flood':
        return <Droplets className="w-7 h-7 text-blue-500" />;
      case 'gas':
        return <Wind className="w-7 h-7 text-purple-500" />;
      case 'medical':
        return <HeartPulse className="w-7 h-7 text-emerald-500" />;
      case 'earthquake':
        return <Activity className="w-7 h-7 text-stone-400" />;
      case 'chemical':
        return <Biohazard className="w-7 h-7 text-rose-500" />;
      default:
        return <ShieldAlert className="w-7 h-7 text-red-500" />;
    }
  };

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 py-6 sm:py-8 space-y-6 text-white">
      {/* Top Bar Navigation & Rapid Utilities */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-slate-900 border border-slate-800 p-3 rounded-2xl shadow-xl">
        <button
          id="btn-back-to-selection"
          type="button"
          onClick={onReset}
          className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-750 px-3.5 py-2 rounded-xl transition-colors cursor-pointer border border-slate-700"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>New Situation</span>
        </button>

        <div className="flex flex-wrap items-center gap-2">
          {/* Live Emergency Dashboard Launch Button */}
          {onOpenLiveDashboard && (
            <button
              id="btn-result-open-live-dash"
              type="button"
              onClick={onOpenLiveDashboard}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold bg-amber-500 hover:bg-amber-400 text-black shadow-md transition-colors cursor-pointer"
            >
              <Activity className="w-3.5 h-3.5" />
              <span>Live Emergency Mode</span>
            </button>
          )}

          {/* SOS Alarm Trigger */}
          {onOpenSos && (
            <button
              id="btn-result-sos"
              type="button"
              onClick={onOpenSos}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-black bg-red-600 hover:bg-red-500 text-white shadow-md shadow-red-600/40 transition-colors cursor-pointer animate-pulse"
            >
              <ShieldAlert className="w-3.5 h-3.5" />
              <span>SOS Alarm</span>
            </button>
          )}

          {/* ICE Medical Profile Button */}
          {onOpenIceModal && (
            <button
              type="button"
              onClick={onOpenIceModal}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold bg-slate-800 text-rose-300 hover:text-rose-200 border border-slate-700 transition-colors cursor-pointer"
            >
              <FileText className="w-3.5 h-3.5 text-rose-400" />
              <span>Medical ID</span>
            </button>
          )}

          {/* Read Aloud */}
          {synthSupported && (
            <button
              id="btn-tts-read-aloud"
              type="button"
              onClick={handleTextToSpeech}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-colors cursor-pointer border ${
                isPlayingAudio
                  ? 'bg-amber-500 text-black border-amber-400 animate-pulse'
                  : 'bg-slate-800 hover:bg-slate-750 text-slate-200 border-slate-700'
              }`}
            >
              {isPlayingAudio ? (
                <VolumeX className="w-3.5 h-3.5" />
              ) : (
                <Volume2 className="w-3.5 h-3.5 text-emerald-400" />
              )}
              <span>{isPlayingAudio ? 'Stop Voice' : 'Read Aloud'}</span>
            </button>
          )}

          {/* Copy Plan */}
          <button
            id="btn-copy-plan"
            type="button"
            onClick={handleCopyPlan}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold bg-slate-800 border border-slate-700 text-slate-200 hover:bg-slate-750 transition-colors cursor-pointer"
          >
            {copied ? (
              <>
                <CheckCheck className="w-3.5 h-3.5 text-emerald-400" />
                <span className="text-emerald-300 font-bold">Copied Plan</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-slate-400" />
                <span>Copy Plan</span>
              </>
            )}
          </button>

          {/* Nearby Help Facilities */}
          {onOpenNearbyHelp && (
            <button
              id="btn-result-nearby-help"
              type="button"
              onClick={onOpenNearbyHelp}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold bg-emerald-600/20 hover:bg-emerald-600/30 text-emerald-300 border border-emerald-500/40 transition-colors cursor-pointer shadow-sm"
            >
              <Hospital className="w-3.5 h-3.5 text-emerald-400" />
              <span>Nearby ERs</span>
            </button>
          )}
        </div>
      </div>

      {/* Main Executive Assessment Card */}
      <div className="bg-slate-900 rounded-3xl shadow-2xl border border-slate-800 overflow-hidden flex flex-col">
        {/* Banner: EMERGENCY TYPE & RISK LEVEL */}
        <div
          id="banner-emergency-status"
          className="bg-slate-950 p-6 sm:p-8 border-b border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-5 relative overflow-hidden"
        >
          <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-red-600 via-amber-500 to-emerald-500 animate-pulse" />

          <div className="space-y-2">
            <div className="flex items-center gap-2.5">
              <div className="w-10 h-10 rounded-2xl bg-slate-900 border border-slate-800 flex items-center justify-center shadow-md shrink-0">
                {getEmergencyIcon()}
              </div>
              <span className="text-xs font-mono font-black uppercase tracking-wider text-red-400">
                ACTIVE TRIAGE DIRECTIVE
              </span>
            </div>

            <h1 className="text-2xl sm:text-3xl lg:text-4xl font-black tracking-tight text-white">
              {assessment.emergencyType}
            </h1>

            {assessment.userDescription && (
              <p className="text-xs text-slate-400 font-medium italic">
                Reported Situation: "{assessment.userDescription}"
              </p>
            )}
          </div>

          <div id="badge-risk-level-container" className="self-start sm:self-center shrink-0">
            <RiskBadge riskLevel={assessment.riskLevel} size="lg" />
          </div>
        </div>

        {/* Card Body */}
        <div className="p-6 sm:p-8 space-y-7 bg-slate-900">
          {/* Situation Context Summary */}
          <div className="p-5 bg-slate-950 border border-slate-800 rounded-2xl space-y-1.5">
            <span className="text-[11px] font-mono font-extrabold uppercase tracking-wider text-slate-400">
              Hazard Telemetry & Immediate Science:
            </span>
            <p className="text-sm sm:text-base text-slate-200 font-semibold leading-relaxed">
              {assessment.summary}
            </p>
          </div>

          {/* CRISIS-SPECIFIC INTERACTIVE TOOL */}
          <section id="section-crisis-specialized-tool">
            <CrisisToolRouter assessment={assessment} />
          </section>

          {/* DO THIS NOW */}
          <section id="section-do-this-now" className="bg-slate-950 p-6 sm:p-7 rounded-3xl border border-slate-800 shadow-xl space-y-4">
            <ActionList
              actions={assessment.doNow}
              completedSteps={completedSteps}
              onToggleStep={toggleStep}
            />

            {assessment.keySafetyRule && (
              <div className="mt-4 p-4 bg-amber-950/70 border border-amber-700/60 rounded-2xl text-xs sm:text-sm font-semibold text-amber-200 flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
                <div>
                  <span className="font-mono font-extrabold uppercase tracking-wider text-amber-300 block mb-0.5">
                    Critical Safety Rule:
                  </span>
                  <span>{assessment.keySafetyRule}</span>
                </div>
              </div>
            )}
          </section>

          {/* 2-Column Split: AVOID & NEXT STEP */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <section id="section-avoid">
              <AvoidList items={assessment.avoid} />
            </section>

            <section id="section-next-step">
              <NextStepCard
                nextStep={assessment.nextStep}
                onGoToNextStep={onGoToNextStep}
              />
            </section>
          </div>

          {/* ADVANCED RESCUE SUITE: 911 Dispatch Script, Multilingual Translation, GPS Beacon, Strobe */}
          <section id="section-advanced-rescue-suite" className="space-y-4 pt-2">
            <Emergency911DispatchScript assessment={assessment} />
            <MultilingualCrisisAlert assessment={assessment} />
            <OfflineLocationBeacon emergencyType={assessment.emergencyType} />
            <VisualStrobeSignal emergencyType={assessment.emergencyType} />
          </section>
        </div>

        {/* Card Footer with Live Monitoring indicator */}
        <div className="p-4 sm:p-5 bg-slate-950 text-white flex flex-col sm:flex-row justify-between items-center gap-3 border-t border-slate-800">
          <div className="flex items-center gap-2">
            <div className="w-2.5 h-2.5 bg-emerald-400 rounded-full animate-ping" />
            <span className="text-xs font-mono font-semibold text-slate-300">
              CRISIS DISPATCH LINK ARMED • EMERGENCY READY
            </span>
          </div>
          <div className="text-xs text-slate-400 font-mono">
            Standard: Verified Emergency Crisis Directives
          </div>
        </div>
      </div>

      {/* Primary Immediate Action Controls */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
        <a
          id="btn-result-call-911"
          href="tel:911"
          className="w-full py-4 px-6 rounded-2xl bg-red-600 hover:bg-red-500 active:bg-red-700 text-white font-black text-base sm:text-lg tracking-wide shadow-xl shadow-red-600/40 flex items-center justify-center gap-3 transition-colors cursor-pointer border border-red-400/40"
        >
          <PhoneCall className="w-5 h-5 animate-bounce" />
          <span>DIAL 911 DISPATCH NOW</span>
        </a>

        <RestartButton
          id="btn-result-new-assessment"
          onClick={onNewAssessment}
          label="New Assessment"
          variant="pill"
          size="lg"
          className="w-full py-4 text-base cursor-pointer bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700"
        />
      </div>
    </div>
  );
};
